name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./

      - name: Set script executable
        run: chmod +x ci.sh

      - name: Deploy on server
        run: ./ci.sh ${{ secrets.remote_server.server }}

