name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -o ./build -v  ./...

      - name: Test
        run: go test -v ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./

      - name: load on server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./build"
          target: "/opt/debt_bot/build"

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: debug list
        run: ls



